### ISSUE TITLE
Add dark theme option

### ISSUE THREAD

**Issue by maxrothman** [open5e/open5e#108]

**Comment by eepMoody** [comment]
ಠ__ಠ

In all seriousness, we should figure out how we want to handle this. The ideal way is to generate a second CSS sheet and load it when the user switches. Probably store their preference in a cookie.

**Comment by maxrothman** [comment]
I actually didn't just add this because I like my hackervision. I think
there's a real use case for people sitting at a slightly dim table using
the site from tablets or phones.

**Comment by maxrothman** [comment]
The most important part of this issue will be deciding whether calling the mode "dungeon mode" is too cute, and where to put the torch on the page when you turn it on.

**Comment by calumbell** [comment]
If nobody is currently working on this, i'd like to take a stab at it this week!

A big part of implementing this feature will be refactoring existing the CSS to use Tailwind utility classes. Once that is out of the way implementing dark mode is fairly simple.

Most sensible place for the toggle feels like the top right corner of the page, but others might have better ideas
