### ISSUE TITLE
Suggestion: compact statblock for monsters.

### ISSUE THREAD

**Issue by GAZ082** [open5e/open5e#139]
Hi there. Would be nice to have a compact statblock for monsters, like those present in the two column SRD document from Wizards. Handy to cop and paste in campaign documents.

**Comment by maxrothman** [comment]
Good idea! Once we've standardized the monster pages with a custom Sphinx domain, we can probably do this pretty easily.

**Comment by txtsd** [comment]
@GAZ082 Do you mean like this?
```
STR  4 (-3)
DEX 16 (+3)
CON 11 (+0)
INT  2 (-4)
WIS  8 (-1)
CHA  6 (-2)
```

**Comment by GAZ082** [comment]
I dont recall how it was 3.5 years ago! But i believe i was refering to something like this that, by the way, already looks like:

![image](https://user-images.githubusercontent.com/100194/68078862-d83c7d80-fdbd-11e9-9c5f-66c4e67784c8.png)
