### ISSUE TITLE
Link up spells that are included in monster/item descriptions

### ISSUE THREAD

**Issue by eepMoody** [open5e/open5e#266]
This one is probably a bit bigger than it seems.

When spells appear in monster or item descriptions, we're going to want to make sure they link to the appropriate spell pages.

The part that makes it bigger and trickier is that we will want this to be an extensible component or directive (powered by slugs?) for a few reasons:

- Previews: if this is a directive, we could async load the spell (using the static API) and display it on hover.
- Parsing: If the parent object (eg. the monster) is included in a set, we could leverage a custom component to fetch all the included child elements without having to parse messy URLS.

This will get a bit tricky because we don't want to clutter the JSON up too much with a bunch of site-specific code. This probably depends on figuring out #265

**Comment by augustjohnson** [comment]
I think you already proposed something like any spell name is manually surrounded by a tag of some sort.  <srd:fire-bolt>Fire Bolt</srd> for example, and then a parser on the front end to make that a link or a hoverbox.

That seems to be the best way to do this, but requires a lot of work that's not done yet (although might be able to be partially automatic?)

I think it has all the data it needs too?  It might need a different name:  Maybe more verbose for clarity:
<dnd-a doc="srd" ref="fire-bolt">Fire Bolt</dnd-a>

**Comment by eepMoody** [comment]
Based on @augustjohnson's suggestion, I broke out the new component work into #277

**Comment by calumbell** [comment]
I believe that this issue has been solved by PR #422. It is now a case of adding the appropriate tags (`<[category]:[slug]>[title]</[category]>`) to our data on the back-end
