### ISSUE TITLE
Sidebar UI behavior

### ISSUE THREAD

**Issue by eepMoody** [open5e/open5e#274]
The sidebar should have collapsible sections and sub-sections, like the existing open5e.com site.

If this can leverage the current route (see existing highlighting for some of what's going on) to expand the current section and any parent sections that would be awesome.

**Comment by calumbell** [comment]
If I have understood this issue correctly, I believe we have resolved it with PR #411. We have collapsing sections and route-based highlighting in the sidebar. Do pipe up if I have missed anything, but for now I am going to mark this issue as resolved.
