### ISSUE TITLE
Make section/markdown pages more automatic

### ISSUE THREAD

**Issue by eepMoody** [open5e/open5e#276]
The current markdown pages under Characters, Combat, Gameplay Mechanics, etc. are obviously super manual. It'd be nice if they were made into a more re-usable component or handled in an completely data-driven way.

**Comment by calumbell** [comment]
I have some time this week and would be happy to take a look into this issue!

I am assuming that what we are after is something closer to how the `/classes` or `/races` route are currently structured. With a nested `index.vue` component containing links to all pages in that section and a `[id].vue` component for displaying each page? Let me know if I am on the right track

**Comment by calumbell** [comment]
With #411 merged into staging I think we are good to mark this issue as closed!
