### ISSUE TITLE
Cross-linking component

### ISSUE THREAD

**Issue by eepMoody** [open5e/open5e#277]
A component or directive should exist that allows us to link to an item directly via its slug. (eg. `fireball` or `necklace-of-fireballs`.

This will (I think) mean generating an index of all the slugs and of what page they should map back to. 

I'm imagining something like `<srd-link slug="fireball">Fireball</srd-link>` that extends the nuxt-link component, which we could add into the Markdown files.

**Comment by calumbell** [comment]
If nobody is currently working on this i'd like to have a go! Any further thoughts how you might want the tags to look in Markdown? For the component itself, I was imagining a `nuxt-link` with a pop-up that appears when you hover with a preview of the linked content.
