### ISSUE TITLE
Scrolling on iOS does not behave as expected.

### ISSUE THREAD

**Issue by augustjohnson** [open5e/open5e#304]
I'm pretty sure on iOS (I tested on Safari and Firefox), most webpages do a weighted scroll, but Open5e does not.

Maybe something here?
https://css-tricks.com/snippets/css/momentum-scrolling-on-ios-overflow-elements/

**Comment by eepMoody** [comment]
@augustjohnson can you check this again and assign back to me if it's still being odd? I did some recent updates that may have resolved it, and it seems to be working on my iPad.

**Comment by calumbell** [comment]
I have just given this a quick test. I visited the live site on iOS (iPhone 11) and the scrolling is definitely weighted. Tested again on Firefox responsive mode with touch simulator engaged, the scroll is definitely weighted.

Not sure when precisely this was fixed, but it looks like it is! I am going to go ahead and close this issue for now, we can reopen it in the event that some weird edge-case is encountered.
