### ISSUE TITLE
Inconsistent spacing of modifiers

### ISSUE THREAD

**Issue by txtsd** [open5e/open5e#311]
The ability modifiers and saving throws have a space between the sign and number when it is a + `(+ 2)`, but have a space before the sign instead when it is a - `( -2)`.

![Screenshot](https://i.imgur.com/ItGgjOB.png)

**Comment by daveycakes** [comment]
this appears to be fixed in the latest staging branch, but is not live

**Comment by calumbell** [comment]
Not sure when precisely this was fixed, but everything looks as it should on the live site. I am going to go ahead and mark this issue as closed

**Comment by txtsd** [comment]
Thank you!
