### ISSUE TITLE
Warlock table has messed up headers

### ISSUE THREAD

**Issue by michaeleconomy** [open5e/open5e#318]
On: https://open5e.com/classes/warlock

The headers (i believe) should read: Cantrips Known, Spells Known, Spell Slots

They currently read:  Cantrips Known | Spells | spell

Thanks Ean for all that you do.

-Michael

**Comment by michaeleconomy** [comment]
this file looked correct: https://github.com/eepMoody/open5e-api/blob/master/data/WOTC_5e_SRD_v5.1/classes.json
 so it's some kind of processing error?

**Comment by calumbell** [comment]
Not sure when this was fixed, but the table headers look good on live and staging.

<img width="924" alt="Screenshot of the Warlock features table" src="https://github.com/open5e/open5e/assets/47755775/dfdecc58-4343-49e1-9651-b489e97e3a0e">

I am going to go ahead and mark this issue as closed. Thanks to whoever sorted it!
