### ISSUE TITLE
Add random number generation to simulate dice rolls

### ISSUE THREAD

**Issue by lhannest** [open5e/open5e#337]
For example, I'm looking at the page for young brass dragons: https://open5e.com/monsters/young-brass-dragon

It would be nice if any text that describes dice rolls would be a hyperlink (bold and red would look nice) that when clicked perform and display the roll by generating a random number.

For example, the `STR 19 +4` when clicked would generate a random 1d20 + 4.
The `Perception +6` would generate a random 1d20 + 6.
The `+7 to hit` when clicked would generate a random 1d20 + 7.
The `2d6 + 4` when clicked would generate a random 2d6 + 4.

Probably you could automatically create a random number generating link for any any regex match of `\d+d\d+( \+ \d)?`.

**Comment by calumbell** [comment]
I have some time this week, i'll take a look at getting this implemented!
