### ISSUE TITLE
Sage Advice Blockquotes are not rendered differently.

### ISSUE THREAD

**Issue by augustjohnson** [open5e/open5e#377]
Originally: https://github.com/open5e/open5e-api/issues/51
![image](https://user-images.githubusercontent.com/827587/226109642-aa6d2430-3f9a-4351-ab50-bb7be324212a.png)

Sage advice blocks are not visually different than the text around it.

This is actually a bug in the markdown file here:
https://github.com/open5e/open5e/blob/master/static/markdown/classes/rogue.md
Or possibly in the vue here:
https://github.com/open5e/open5e/blob/master/pages/classes/rogue.vue
The issue is that vue renderer does not seem to respect the blockquote.

**Comment by peterbinks** [comment]
fwiw - i see that section rendering inside of a `blockquote` element, i assume there just aren't styles associated with it?  are there any examples of a blockquotes currently on the site?
