### ISSUE TITLE
The open5e organization needs a README, and to fix a couple of typoes

### ISSUE THREAD

**Issue by augustjohnson** [open5e/open5e#378]
https://github.com/open5e
Right now, the open5e organization not the repo has a typo in the description of the org.
Also, there's a prompt for the readme, and we dont' have an org-level readme at the moment. 

"An open resource and API for the 5th edition d20 system, including a variety of OGL-licensced content."
Typo on **licensced**

**Comment by eepMoody** [comment]
That's an excellent point. 

I think in the spirit of this being a very collaborative project right now, it'd be a good thing to write together.

I'm gonna drop some stuff from the existing readme's and suggestions in an editable doc and share it in the Discord, so folks can go at it.

**Comment by calumbell** [comment]
Looks like this issue has been marked as *Done* on the roadmap but isn't quite resolved yet. The README looks great, but we still have that typo in the org description:

<img width="645" alt="Screenshot 2024-03-21 at 12 29 55" src="https://github.com/open5e/open5e/assets/47755775/b43573fc-b761-4a6d-9f1f-f1c31743cb4e">

Would be happy to fix it myself, but I think only the owner has permission to change this field. @eepMoody mind taking a look at this when you have a moment?

**Comment by eepMoody** [comment]
Finally fixed!
