### ISSUE TITLE
UI layer is making a 301 to prepend a / to API calls.

### ISSUE THREAD

**Issue by eepMoody** [open5e/open5e#384]
![image](https://github.com/open5e/open5e/assets/6200445/8eade6c5-8264-4741-8d50-5bd6968f9302)

This is introducing a small delay on all API calls.

**Comment by augustjohnson** [comment]
Just to quantify the delay, that particular call took ~100ms for the top one and ~500ms for the bottom one. So on the more stressful calls this might be ~20% increase in data load time, but for faster calls it may be up to like 50% for data load time, although those are faster so people mostly don't care.

**Comment by calumbell** [comment]
This issue was fixed in #400. This error is no longer appearing on either the beta site or on my fork, but it doesn't look like the fix has been pushed to production yet. Whenever an admin has a moment, would they be able to mark this issue as closed?
