### ISSUE TITLE
Search endpoint should be scoped to selected sources

### ISSUE THREAD

**Issue by eepMoody** [open5e/open5e#408]
Want to explore a half-measure on this.

User feedback is that they expect this to honor their source selections. But If we hide it something silently because of a source selection it might be assumed it wasn't there.

I believe the correct resolution here is a hybrid solution, where we execute the search query against the entire dataset.
Then on the UI layer, we can hide the non-matching results behind a "view additional results from other sources" kind of button?

<img width="535" alt="image" src="https://github.com/open5e/open5e/assets/6200445/d82ba222-ce42-42e5-a35c-a6598057bd36">

<img width="624" alt="image" src="https://github.com/open5e/open5e/assets/6200445/6ec59cb4-7da5-4bff-8823-d6f33d3b7289">

**Comment by calumbell** [comment]
I am taking a look at this today. Going to take some extra time to give the `/search` page a little refactor while I am here, it needs one!
