### ISSUE TITLE
Conditions endpoints cause 500 errors

### ISSUE THREAD

**Issue by eepMoody** [open5e/open5e#414]
Eg. https://open5e.com/conditions/charmed

SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON

**Comment by tbasten** [comment]
It seems like this is no longer an issue? I tried a number of conditions and they rendered without issue.

**Comment by calumbell** [comment]
Good spot, thanks for flaggin! Looks like this has been fixed on the `staging` branch. It is still busted on the live site, but it should fix itself when we next update. I am going to go ahead and close this issue.

Couldn't help but notice that there is a link to a non-existant `/conditions` route in the breadcrumbs, I am going to go ahead and open an issue to get that fixed.

<img width="1049" alt="open5e dead link in breadcrumbs" src="https://github.com/open5e/open5e/assets/47755775/aff177f0-28c3-4c7b-817b-227a7f84b325">
