### ISSUE TITLE
Add source filtering to new class, race, combat, etc. endpoint calls

### ISSUE THREAD

**Issue by eepMoody** [open5e/open5e#415]
@calumbell introduced a number of awesome new dynamic sections in https://github.com/open5e/open5e/pull/411

These were developed in parallel with the new source-selection system, so they need to be updated to use the pinia store for requesting their resources, and should respect the source selection for the top-level pages (but not for individual items)

**Comment by calumbell** [comment]
Looks like this issue was fixed in PR #503 as a side-effect of moving our data fetching off of Pinia and on to Vue Query. I'll go ahead a mark this issue as closed
