### ISSUE TITLE
Bug: remove saving throws that are the same as ability modifiers from monster stat-blocks

### ISSUE THREAD

**Issue by calumbell** [open5e/open5e#464]
In monster stat-blocks published by Wizards of the Coast and Level Up Advanced 5e, the saving throws section only lists those saving throws that are different from the base ability modifier.

Currently, on the Open5e live site, the Saving Throw section lists all of the different saves, including those that are the same as the base modifier.

For example, if you look at the page for the [adult brass dragon](https://open5e.com/monsters/adult-brass-dragon) (which pulls from [this API endpoint](https://api.open5e.com/monsters/adult-brass-dragon/)), the saving throws read:

**Saving Throws** Str +6 , Dex +5 , Con +10 , Int +2 , Wis +6 , Cha +8

But we would like to filter out all of the saves that are the same as the ability modifier, which would look like:

**Saving Throws** Dex +5 , Con +10 , Wis +6 , Cha +8

**Comment by christophermiles** [comment]
I’d love to take this as my first issue!
