### ISSUE TITLE
Refactor: expanded and compact monster stat-blocks

### ISSUE THREAD

**Issue by calumbell** [open5e/open5e#466]
As of PR #412 we have had compact monster statblocks on the Open5e site. While this is a great feature, there are a few problems with its current implementation

- The expanded and compact statblocks are on completely different routes, and use different page components. This is proving difficult to maintain as the logic on the two pages has already begun to diverge.
- The URLs on the compact statblocks kind of torpedo the site breadcrumbing, implying the existance of a non-existant `/monsters/compact` route.

### Solution

As both the expanded and compact statblocks pull from the same API endpoint, I feel that these two pages (`/monsters/[id]` and `/monsters/compact/[id]`) should be collapsed into just the `/monster/[id]` page. The user should be able to toggle between the expanded and compact form of the statblock using a button. Ideally, the styles would match exactly the current expanded and compact styles.

Toggling this setting should only modify the page styles, and perhaps control the conditional rendering of elements that might not be appropriate to include in the compact stat-block. Additionally, it would be good if the toggle state was controlled by a query param (ie. `monsters/goblin?compact`) so that the compact statblock can be linked to directly.

### Notes

- To avoid link rot, a redirect from the `/monsters/compact/[id]` to the `/monsters/[id]` should be added.

**Comment by christophermiles** [comment]
Keen to take a crack at this one!

**Comment by christophermiles** [comment]
I wonder if it makes sense for this to be a global preference, like light/dark mode? What is the typical use case for viewing a compact stat block?

**Comment by calumbell** [comment]
Awesome! Thanks for picking this one up

> I wonder if it makes sense for this to be a global preference, like light/dark mode? What is the typical use case for viewing a compact stat block?

I was thinking the same thing, but it would be worth considering who this would interact with the query parameter. 
The use case provided in the origin feature request  (#139) was that they are useful for copying and pasting directly into campaign documents without taking up too much space
