### ISSUE TITLE
Bug: Monster pages missing condition immunities

### ISSUE THREAD

**Issue by calumbell** [open5e/open5e#471]
(Thanks to PhazeLink on Discord for flagging this one)

The condition immunities of monsters are returned by the API, but are not being displayed on the website. It would be could if we could add these to the `/monsters/[id].vue` page, probably after the *Damage Immunities*.

### Reproduction

1) Visit the page of a monster with condition immunities on the Open5e live site. The [Bar Brawl](https://open5e.com/monsters/bar-brawl) was flagged in the original Discord post. Notice that there are no condition immunities in the statblock.

2) Compare this with the [Open5e API page for the Bar Brawl](https://api.open5e.com/monsters/bar-brawl/), which returns conditions immunities

<img width="676" alt="Screenshot 2024-03-01 at 22 06 49" src="https://github.com/open5e/open5e/assets/47755775/d4cdd783-4d58-4ab4-8a8d-cd8305a6e13f">

<img width="807" alt="Screenshot 2024-03-01 at 21 53 39" src="https://github.com/open5e/open5e/assets/47755775/681cf066-027d-48cc-b4a1-bc46281f335c">

**Comment by Jayanth-Parthsarathy** [comment]
Hey @calumbell. I would love to work on this. Can you please assign this to me?

**Comment by Jayanth-Parthsarathy** [comment]
And for reference you mean something like this right? 

![image](https://github.com/open5e/open5e/assets/86654557/899b98b5-2117-42c7-8b41-01f9516e72ac)
