### ISSUE TITLE
Standardize all Vue pages to use the Composition API and <script setup>

### ISSUE THREAD

**Issue by Sturlen** [open5e/open5e#488]
Currently pages are split between using the old Options API and the newer Composition API. Several pages are using both at the same time. This makes it difficult to maintain and refactor, and does not play well with newer libraries.

My suggestion is to move everything to the newer <script setup>, since that is the new standard. I should be able to implement the changes myself.

More context on the benefits of the Composition API: https://vuejs.org/guide/extras/composition-api-faq.html

**Comment by calumbell** [comment]
Great idea, this has been bothering me for ages.

@Sturlen let me know if you'd like to have a go at fixing this issue, I can assign it to you. I'd also be happy to look into it also but I wouldn't have time for a few weeks yet.

Worth noting that getting the Pinia store to play nice with the Compositions API on page components might require a little finessing.

**Comment by Sturlen** [comment]
@calumbell I'd be happy to give it a go. Assign away.

**Comment by calumbell** [comment]
Done! (Not after accidently assigning to myself first)

**Comment by calumbell** [comment]
With #496 and #497 merged to staging, I think we can close this issue as resolved. Thanks for making the fix @Sturlen!
