### ISSUE TITLE
Feature Request - API in other languages (German...)

### ISSUE THREAD

**Issue by mortensen** [open5e/open5e#502]
The SRD is available in german too. It would be awesome to see the API have support for that language too. I guess it will be more than just a language flag, because then its not called item or feat or spell. Instead maybe the objects are called diferent. But the best aproach should be checked before implementing it.

**Comment by mortensen** [comment]
German SRD:


https://codeberg.org/nesges/SRD-5.1-DE

Parsed files

**Comment by Xysto** [comment]
For what it's worth, I am available to contribute for the french language (I do not guarantee the time it will take me to do the whole SRD).

It will be nice to have a collaborative tool with the "missing translations" compared to the english version so anyone can contribute time to time to fill out the blank. Is that possible ? With maybe the PR system of Github ?

And if the feature is available on the API but the translation not over, we can imagine that there is a default fallback on the English version of the object. Does that make sens ? (to be clear I do not have the skills to contribute to the implementation of the "language feature", only the translation in french)

**Comment by mortensen** [comment]
@Xysto WotC released the SRD already in 5 languages including frensh:

https://dnd.wizards.com/fr/resources/systems-reference-document 

Its less of a Translation issue i guess but more a question on how to alter / extend the API programmatically. And there is already a v2 in work for the API.

I would hope in the end the tags / objects will still be referenced in English and just filled with the translated text which can be sent in via a new optional language flag... Maybe a mapping table for keywords that need to be translated. That's where we could maybe help out.

 Example: key "Cost" in German may be "Preis" or "Kosten". To be able to get the German text from the SRD source.

**Comment by Xysto** [comment]
Yes of course, I did not make my point very clear sorry. I know the translation is already [here](https://media.wizards.com/2023/downloads/dnd/SRD_CC_v5.1_FR.pdf) but as I understood, it is more than painful to parse automatically the SRD's pdf to the json format that Open5e is using (I truly understand why). My proposal was to help to manually import the french SRD to the json format if there is no other choice.

As for the V2 API, I also understood that it will be a huge breaking change for the data format as well. Do you know if there is a way to participate to the discussion or if there is a workgroup that I can join to maybe contribute on that part also? Is there a wip json schema or something similar? I only have this [project](https://github.com/orgs/open5e/projects/6) for reference.

**Comment by augustjohnson** [comment]
I think that the general way to support this is that the SRD in German is a new document.
The API should reasonable support this without too much trouble. Here are a few things that could be problems:
1. UTF-8? Is that standard enough in all of our presentation layers?
2. Document selection UI? - Just adding it as another document is a little strange, but it's not the WRONG approach.
3. Mapping a given item in one language to the same item in another language? - This is a complex interaction.

**Comment by mortensen** [comment]
UTF-8 should be sufficient for french, German, italian, English and spanish.

**Comment by mortensen** [comment]
See https://github.com/open5e/open5e-api/issues/457 for the work on the german source file.
@Xysto Feel free to create a similar ticket for french if you´d like :)

**Comment by calumbell** [comment]
It looks like this issue has been transferred to the API repo (https://github.com/open5e/open5e-api/issues/457). As this doesn't really have anything to do with the front-end (yet!) I am going to go ahead and close this issue.

Once we have the SRD in German available on the API we can think about how we might it on the front end
