### ISSUE TITLE
Feature: pagination on the /monsters top-level page

### ISSUE THREAD

**Issue by calumbell** [open5e/open5e#508]
Loading times on the https://open5e.com/monsters route are currently extremely slow. On a solid internet connection (~200 Mbps) I am observing >4s load times. Taking a look at the debug console, and it looks like this is due to this route requesting every monster in when it loads. Assuming no filters are applied, that is close to 2900 entries in one go!

One solution to this would be to add pagination to this page – chunking the monster list into blocks of 25-50 and then only requesting them when needed. A recent update to our data fetching infrastructure (PR #503) will likely make this fix much, much simpler. 

By my reckoning, this fix can be split into three tasks:

1) Update data fetching composables (`useAPI()`, etc.) to support pagination. This might involve passing an optional parameter to specify which pages to return.
2) Update UI so that the user can navigate between pages (UI on `/pages/spells/index.vue`might be a good starting point)
3) Play around with various pagination values (page size, number of pages to load at a time, etc) until the user-experience is smooth.

Once this is fixed, we will likely roll out similar updates to the `/spells` and `/magic-items` routes.

NB. While pagination exists on the [spells top-level page](https://open5e.com/spells), this is purely a UI feature. The page still requests every spells in one go, which leads to long load times.

**Comment by Sturlen** [comment]
With the new standard API table component in place, we can use that to implement pagination for all pages that use it. I think is best done through a new `usePaginated` composable inside the table component that handles all the logic. 

@calumbell If you haven't already started work on this, then I'd like to be assigned. Already have a working prototype so it should go pretty smooth.

**Comment by calumbell** [comment]
@Sturlen done!
