### ISSUE TITLE
Feature: Use standard tables for all large list pages

### ISSUE THREAD

**Issue by Sturlen** [open5e/open5e#509]
Currently the pages that list a large amount of items (monsters, spells and magic items) are all structured differently. Some are grouped by first letter, some by spell level and some in table. 

I suggest using the same table components and filtering system for all of these. This makes the user experience more consistent and simplifies development. Features like pagination #508 will then only have to be implemented once.

This can also easily be expanded to all list pages, but is less necessary for routes with only a couple items.

**Comment by calumbell** [comment]
I agree. This sounds like a good idea. Long term it will be easy to maintain, and it should ensure a consistant style and user experience across the different pages.

However we wouldn't want every table to be *exactly* the same. You'd want to display different information on the tables for different endpoints. If i was looking at `/spells`, for example, i'd probably want to see its level, school and which classes can learn at a passing glance, right there on the table before clicking through to a specific spells page. On `/monsters` i'd want to know what type of creature it was, its size and CR. And so on.

**Comment by Sturlen** [comment]
> However we wouldn't want every table to be _exactly_ the same. You'd want to display different information on the tables for different endpoints.

My point was more that the tables should use the same Row and Column components and use the same sorting and filtering logic. Column headers and contents should be customizable per page.

**Comment by calumbell** [comment]
That makes a lot of sense, do you reckon that we should postpone working on pagination until we have implemented the standardised tables?

I have some time this coming week and am happy to have a go at implementing this. Let me know if you have already made a start on this and I can focus on a different issue

**Comment by Sturlen** [comment]
Standardizing first would make a lot of sense. I've not done any work on it yet so feel free.
