### ISSUE TITLE
UX: retain filter settings when navigating back to `/monsters` page

### ISSUE THREAD

**Issue by calumbell** [open5e/open5e#529]
## Description
Clicking on a link from the `/monsters` route to open a monster page and then clicking back to the return to the full list clears the state of the monster filters. This can be extremely frustrating when browsing through multiple statblocks using the filters.

![ezgif com-optimize](https://github.com/open5e/open5e/assets/47755775/e47989ba-4944-4d5d-9838-8115a46aa670)

## Recreation
1. Checkout the `staging` branch
2. Visit the `/monsters` route and set the filters
3. Click any link in the list to view that monster's page
4. Click the back button on the browser to return to the `/monsters` route. The filters have been reset
 
## Solution
Having website remember filter state when navigating back to the /monsters route should solve this issue. Whether filter state should be retained in other contexts is a point worth discussing. Two possible avenues to explore to solve this issue might be A) store the monster filter form state are URL params, or B) save filter preferences in local storage

**Comment by christophermiles** [comment]
@calumbell Could there be an Option C of just storing in a composable like `useMonsterFilterSettings` that exposes some singleton state? It would maintain the filter settings for the current session but would not survive across sessions, but could be extended to read from and save to local storage o satisfy Option B.

Option A is kind of nice though since it would allow a user to bookmark a query, if we thought that was a typical use case.

**Comment by calumbell** [comment]
@christophermiles So, the filtering architecture for all the top-level pages has been overhauled on the [V2 API branch](https://github.com/open5e/open5e/tree/feature/v2-api). There is now a single `<api-table-filter>` component that can filter the API results on any endpoint. If you'd like to work on this issue (which would be awesome), it is probably best to do so on the `V2 API` branch, or wait until this branch gets merged to `staging` (which should be soon)

Option C sounds like a really good approach! My only comment is that the `useMonsterFilterSettings` composable should called from within whichever component handles the filtering, as putting this state on the page component might get a bit messy.

I agree with you w.r.t. Option A. I struggle to see many use-cases for this. The only one I can think of is filtering spells by class

**Comment by christophermiles** [comment]
D&D Beyond uses query parameter for the filter state. 🤔
