### ISSUE TITLE
Solution to redirect links to moved v1 items

### ISSUE THREAD

**Issue by eepMoody** [open5e/open5e#545]
To avoid linkrot (and the resulting hit to search rankings) we should strive to redirect as many queries to existing items and pages as possible.

Solutions to this issue should suggest a strategy that either: 

1. allows links to fall back to v1 endpoints and/or pages if a relevant v2 item does not exist
2. automatically redirect users to the appropriate v2 page for missing items

This does not need to be 100% effective or bulletproof. Where tradeoffs need to be made, a solution should prioritize our most-searched and most-linked types of pages: monsters, spells, and items.

**Comment by calumbell** [comment]
Do correct me if I am wrong (I am not fully up to speed with latest developments on API v2), but I believe we can (and should) switch over to to consuming version 2 of the API without changing the existing site-map. `/monsters/goblin` Should pull from V2 if it is available, if not V1. It doesn't make sense to me to have seperate pages on the front-end for different API versions (ie. `/monsters/v1/goblin` and `/monsters/v2/goblin`), but I could well be misinterpretting your meaning.

If the response structures for V1/V2 are too different to handle on a single page component, we could write template components for rendering each flavour of response and conditionally render these based on what the API returns.

If we want to surface which API version a given page is pulling from we could add a link to the API endpoint the page pulls from to the markup.

wrt. your bullet-points:
1. We can probably handle this by updating the logic in the data fetching composables. Perhaps running `useMonster()` will first hit the V2 `/monsters` endpoint, then V1 if that fails, and finally throw an error if both fail.
2. I don't feel like there should be different pages on the front-end for rendering results returned by V1 & V2 of the API. We can create templates to handle rendering data return from different API versions and conditionally render them as needed on the page

**Comment by calumbell** [comment]
I have had a look into this, and extending our existing redirect middleware probably won't work in this. The problem is that many of the primary keys for items in the Open5e database have changed between versions 1 and 2, but these changes aren't especially regular, so look-up tables with find/replaces won't really cut it.

Perhaps we could you the `/search` endpoint to search for the key requested and redirect the user to the most relevant result returned?
