### ISSUE TITLE
Update Documents to v2 endpoint

### ISSUE THREAD

**Issue by eepMoody** [open5e/open5e#546]
This is an ideal first step to moving our content to the new endpoints. The source selection modal (the primary consumer of documents) is the primary set of values that drive all other queries.

Key Tasks:
- [ ] Update documents endpoint to retrieve v2 documents
- [ ] Update store to store new document format, inclusive of new `ruleset` property
- [ ] Update modal to use new values
  - [ ] This should include at least a display of ruleset per-document
  - [ ] Ideally this includes a "ruleset" selector that filters the available documents (and automatically deselects hidden documents)
- [ ] Update API definitions to include new document selections
  - [ ] It is okay if this breaks those API definitions, unless they have been already updated to v2.

**Comment by calumbell** [comment]
I'll take a stab at this, I have some time this week. Just a couple of questions before I make a start:

1) Any guidance on how sources modal menu should look? My idea, based on the text above:
a) documents should remain sorted by publisher but indicate somewhere which `ruleset` they relate to, perhaps in a piece of UI similar to the `<source-tag>` component.
b) A Select menu could be added near the top of the modal to pick a ruleset. This will default to undefined, but once a ruleset is selected, all items in that ruleset will be selected and all items outside of it deselected. Perhaps all sources outside of the current ruleset can be hidden in modal.
2) By 'Update API definitions to include new document selections', do you mean updating the `/api-docs` route, or updating that composables which handle data fetching from the API? (A necessary step to getting this feature implemented)
