### ISSUE TITLE
Update UI to V2 API

### ISSUE THREAD

**Issue by eepMoody** [open5e/open5e#549]
This has been created as a standalone project due to its size. Tracked here https://github.com/orgs/open5e/projects/8

**Comment by christophermiles** [comment]
@eepMoody I have been browsing tickets that I could help with and happened to notice this is still open, but it looks like the tickets in the standalone project are all done. Not sure if you wanted to close this off?

**Comment by calumbell** [comment]
All the work of moving the front-end to V2 of the Open5e API is done. All endpoints have been moved from V1 -> V2 equivelents. It is probably high time to merge to `staging`. I'll do a final pass, push the last bits of code I have been working on for that branch, and open a PR (likely tomorrow)
