### ISSUE TITLE
Update Spells to v2 endpoint

### ISSUE THREAD

**Issue by eepMoody** [open5e/open5e#558]

**Comment by 09362087268** [comment]
خوبه

**Comment by 09362087268** [comment]
خیلی خوبه

**Comment by calumbell** [comment]
Not sure the exact PR where this was resolved, but on the `feature/v2-api` branch the we are pulling spells from the V2 API endpoint and the website seems pretty happy about it!

I'll go ahead and mark this issue as resolved, please reopen if I have overlooked something!
